import axios from 'axios'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'

import Tree from '@/components/Tree'
import styles from '@/styles/OtherTree.module.css'
import { Tree as TreeType } from '@/types/tree'

export default function UserTree() {
	const [trees, setTrees] = useState<TreeType[]>([])
	const router = useRouter()
	const userId = router.query.id as string

	useEffect(() => {
		;(async () => {
			const treeRes = await axios.get<TreeType[]>(`http://localhost:8000/${userId}/tree`)
			setTrees(treeRes.data)
		})()
	}, [])

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<meta
					property='og:image'
					content={`https://h23s-20-frontend.vercel.app/api/og/${userId}`}
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className={styles.tree}>
				<Tree trees={trees} />
			</div>
		</>
	)
}
