import Head from 'next/head'
import { useRouter } from 'next/router'

export default function UserTree() {
	const router = useRouter()
	const userId = router.query.id as string

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<meta
					property='og:image'
					content={`https://h23s-20-frontend.vercel.app/api/og/${userId}`}
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
		</>
	)
}
