import { Inter } from 'next/font/google'
import Head from 'next/head'
import { RecoilRoot } from 'recoil'

import AuthProvider from '@/components/AuthProvider'
import { initMock } from '@/mocks/main'
import '@/styles/globals.css'

import type { AppProps } from 'next/app'

const inter = Inter({ subsets: ['latin'] })

initMock()

export default function App({ Component, pageProps }: AppProps) {
	return (
		<>
			<Head>
				<title>進捗が木になる～</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={inter.className}>
				<RecoilRoot>
					<AuthProvider>
						<Component {...pageProps} />
					</AuthProvider>
				</RecoilRoot>
			</main>
		</>
	)
}
