import { Inter } from 'next/font/google'
import Head from 'next/head'
import Setting from '@/components/setting'
import styles from '@/styles/Home.module.css'
import Ranking from '@/components/ranking'
import UserID from '@/components/userID'
import Evaluation from '@/components/evaluation'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={`${styles.main} ${inter.className}`}>
				<div>
					<Setting />
					<Ranking />
					<UserID />
					<Evaluation />
				</div>
			</main>
			
		</>
	)
}


