import { Inter } from "next/font/google"
import Head from "next/head"
import Image from "next/image"
import { GetWindowSize } from "./GetWindowSize"

import styles from "@/styles/ranking.module.css"
import { useEffect, useRef,useState } from "react"
import axios from "axios"
import {Ranking} from "@/types/ranking"
import Link from "next/link"

const inter = Inter({ subsets: ["latin"] })

export default function Ranking() {
    const { height, width } = GetWindowSize();

    const top = [30, 19, 33, 14, 70, 76, 70, 68];
    const left = [18, 42, 63.5, 84.5, 17, 33, 66, 90];

    const  [data, setData] = useState<Ranking[]>();

    useEffect(()=>{
        const fetch=async ()=>{
            const res=[
                {
                    user_id:"mehm8128",
                    points:100
                },
                {
                    user_id:"mehm8128",
                    points:90
                },
                {
                    user_id:"mehm8128",
                    points:80
                },
                {
                    user_id:"mehm8128",
                    points:70
                },
                {
                    user_id:"mehm8128",
                    points:60
                },
                {
                    user_id:"mehm8128",
                    points:60
                },
                {
                    user_id:"mehm8128",
                    points:60
                },
                {
                    user_id:"mehm8128",
                    points:60
                },
            ]
            setData(res);
        }
        fetch();
    },[])
    
    return (
    <>
        <Head>
            <title>ranking</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={`${styles.main} ${inter.className}`}>
            <img
                className={styles.background}
                src="/background.png"
                alt="background tree"
                height={height}
                width={width}
            />
            {!data ? 0 : data.map((item, index) => (
                <div className={styles.ranking} style={{
                    top: `${top[index]}%`,
                    left: `${left[index]}%`,
                    fontSize: `${width/6}%`,
                }} id={"rank" + (index + 1)} key={item.user_id}>
                    <div className="id">{item.user_id}</div>
                    <div className="point">{item.points}pt</div>
                </div>
            ))}
            {/* <Link href="./" className={styles.btn}><img src="/home_back.png" height={Math.min(height/500, width/400)} width={Math.min(height/500, width/400)}></img></Link> */}

            <Link className={styles.btn} href="./">
                <Image
                    className={styles.btmImg}
                    src="/home_back.png"
                    alt="homeBtn"
                    
                    height={height / 6 > width / 6 * 357 / 551 ? width / 6 * 357 / 551 : height / 6}
                    width={height / 6 > width / 6 * 357 / 551 ?  width / 6 : height / 6 * 551 / 357}
                />
            </Link>
        </main>
    </>
	)
}
