import { Inter } from "next/font/google"
import Head from "next/head"
import Image from "next/image"
import { GetWindowSize } from "./GetWindowSize"

import styles from "@/styles/ranking.module.css"
import { useEffect, useRef,useState } from "react"
import axios from "axios"
import {Ranking} from "@/types/ranking"

const inter = Inter({ subsets: ["latin"] })

export default function Ranking() {
    const { height, width } = GetWindowSize();

    const top = [35, 15, 38, 12, 70, 80, 78, 82];
    const left = [7, 30, 60, 76, 4.5, 25, 56, 81.5];

    const  [data, setData] = useState<Ranking[]>();

    useEffect(()=>{
        const fetch=async ()=>{
            const res=[
                {
                    user_id:"mehm8128",
                    points:100
                },
                {
                    user_id:"mehm8128",
                    points:90
                },
                {
                    user_id:"mehm8128",
                    points:80
                },
                {
                    user_id:"mehm8128",
                    points:70
                },
                {
                    user_id:"mehm8128",
                    points:60
                },
                {
                    user_id:"mehm8128",
                    points:60
                },
                {
                    user_id:"mehm8128",
                    points:60
                },
                {
                    user_id:"mehm8128",
                    points:60
                },
            ]
            setData(res);
        }
        fetch();
    },[])
    
    return (
    <>
        <Head>
            <title>ranking</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={`${styles.main} ${inter.className}`}>
            <Image
                className={styles.background}
                src="/background.png"
                alt="background tree"
                height={height}
                width={width}
            />
            {!data ? 0 : data.map((item, index) => (
                <div className={styles.ranking} style={{
                    top: `${top[index]}%`,
                    left: `${left[index]}%`,
                }} id={"rank" + (index + 1)} key={item.user_id}>
                    <div className="id">{item.user_id}</div>
                    <div className="point">{item.points}pt</div>
                </div>
            ))}
        </main>
    </>
	)
}
